repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: mixed-line-ending
      args: [ --fix=lf ]
    - id: trailing-whitespace
      args: [ --markdown-linebreak-ext=* ]
    - id: check-yaml
      args: [ --unsafe ] # else crds become invalid because of included enums with operators
      exclude: "^.*\/templates\/.*$" # exclude files in templates folder because they are not valid yaml anyway
    - id: check-json
    - id: check-merge-conflict
    - id: detect-aws-credentials
      args: [ --allow-missing-credentials ]
    - id: double-quote-string-fixer
    - id: end-of-file-fixer

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.76.0
  hooks:
    - id: terraform_fmt
    - id: terraform_checkov

- repo: https://github.com/terraform-docs/terraform-docs
  rev: "v0.16.0"
  hooks:
    - id: terraform-docs-go
      args: ["markdown", "table", "--output-file", "README.md", "--output-mode", "inject", "./"]
